require "game/util/color"

--Window Parameters and Engine Graphics
FULLSCREEN = true
WINDOW_WIDTH = 2000*0.4
WINDOW_HEIGHT = 1374*0.4
MSAA = 4

QUALITY_SCALE = 4

LAYER_COUNT = 5
LAYERS = {
	TERRAIN = 1,
	ROADS = 1.3,
	CITIES = 1.6,
	UNITS = 2,
	MAP_CONTROL = 3,
	UNIT_CONTROL = 4,
	TEXT = 5,
}

--TODO: Registry?
Enum_StandingOrders = {
	SKIP = 1,
	FORTIFY = 2,
	HEAL = 3,
}

--Debug Flags
DEBUG = false
DRAW_BOUNDS = false
SPLASH = false
QUIT_ON_ESCAPE = false

--Colors
DEBUG_COLOR = COLORS.WHITE
DEBUG_TEXT_COLOR = COLORS.WHITE

UI_COLOR_PRIMARY = COLORS.GRAY --COLORS.GRAY
UI_COLOR_SECONDARY = COLORS.BLACK

CITY_UI_COLOR_PRIMARY = COLORS.DARK_GRAY
CITY_UI_COLOR_SECONDARY = MakeColor(64, 48, 117)

--DBG
UI_COLOR_SECONDARY = CITY_UI_COLOR_SECONDARY

--Formatting
DEFAULT_TEXT_WIDTH = 130
DEFAULT_UI_ROUNDNESS = 10

--Game Flags
ALT_MAP_DRAW = true
JUTTER = false        --Remove movement interpolation for units
REVEAL_ALL = false