GRID_WIDTH = 150
GRID_HEIGHT = 100

HEX_RADIUS = 30
HEX_RADIUS_SHORT = HEX_RADIUS * math.sqrt(3) / 2

MIN_ZOOM = 0.6
MAX_ZOOM = 2

TUNING = {
	WORLDGEN = {
		PLATE_COUNT = 15,
		WATER_RATIO = 0.6,

		RIDGE_CHANCE = 1,
		RIDGE_ELEVATION = 11,
		MOUNTAIN_CUTOFF = 10,

		HILL_CHANCE_PER_ELEVATION = 16,
		FOREST_CHANCE = 4,

		RELAX_ITERS = 2,
		HEAT_ITERS = 0,
		MOISTURE_ITERS = 50,
		LAND_PERTURB_ITERS = 5,
		BIOME_PERTURB_ITERS = 5,

		HEAT_DEPOSIT_SIZE = 1,
		HEAT_WATER_MULT = 5,

		OCEAN_MOISTURE = 30,

		LEGACY = {
			--Every 1 out of this number cells will have a hill
			HILL_CHANCE = 8,

			MOUNTAIN_COUNT = 30,
			MOUNTAIN_SPREAD_CHANCE = 3,

			FOREST_COUNT = 30,
			FOREST_SPREAD_CHANCE = 2,

			RIVER_COUNT = 20,
			MIN_RIVER_LENGTH = 4, --Ignored
			MAX_RIVER_LENGTH = 20, --Ignored
			RIVER_LENGTH = 30,
		}
	},

	GAMEPLAY = {
		HEAL_PER_TURN = 15,

		SCIENCE_PER_POP = 1,

		PRODUCTION_FROM_FOREST = 10,
	},

	UI = {
		FLOATER_DURATION = 2,
		DAMAGEFLOATER_OFFSET_X = 30,
		YIELDFLOATER_OFFSET_Y = -30,
		FLOATER_OFFSET_Y = -20,

		CITY_MANAGEMENT = {
			CITIZEN_COIN_OFFSET_Y = -50,
			CITIZEN_COIN_SCALE = 0.5,
		},
	},

	ENGINE = {
		CONSOLE_HISTORY_SIZE = 20,
		TEXTENTRY = {
			CURSOR_TICK = 1,
		},
	},

	--COLORS
	HP_BAR_BG = COLORS.BLACK,
	HP_BAR_FG = function(current, max)
		local ratio = current / max
		if ratio > 0.7 then return COLORS.GREEN end
		if ratio > 0.3 then return COLORS.YELLOW end
		return COLORS.RED
	end,

	--SENSITIVITY
	DEFAULT_CAMERA_PAN_TIME = 0.25,
	CAMERA_MOVE_SPEED = 400 * 2,
	CAMERA_MIN_SPEED = 10*HEX_RADIUS*2, --Pixels per second

	UI_SCROLL_SPEED = 10,

	UNITS_SCALE = 0.6,
	YIELDS_SCALE = 0.6,

	CITY_VIEW_RANGE = 3,
	CITY_WORK_RANGE = 3,
	CITY_EXPANSION_RANGE = 5,
	DEFAULT_UNIT_VIEW_RANGE = 2,
	DEFAULT_CITY_VIEW_RANGE = 2,

	SETTLEMENT_SPACING = 3,
}